<Project>

	<Import Project="$([MSBuild]::GetPathOfFileAbove('Directory.Build.props', '$(MSBuildThisFileDirectory)..'))" />

	<!-- NuGet package metadata shared by every library package -->
	<PropertyGroup>
		<Authors>Dmitry Kovyazin</Authors>
		<Company>BrandUp</Company>
		<PackageProjectUrl>https://github.com/brandup/BrandUp.Extensions.ObjectStorage</PackageProjectUrl>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<PackageIcon>icon.png</PackageIcon>
		<GenerateDocumentationFile>True</GenerateDocumentationFile>
		<NoWarn>$(NoWarn);CS1591</NoWarn>
	</PropertyGroup>

	<ItemGroup>
		<None Include="$(MSBuildThisFileDirectory)..\README.md" Pack="true" PackagePath="\" />
		<None Include="$(MSBuildThisFileDirectory)..\icon.png" Pack="true" PackagePath="\" />
	</ItemGroup>

</Project>
